export { routes as authRoutes } from "./auth.routes";
export { routes as profileRoutes } from "./profile.routes";
export { routes as postRoutes } from "./post.routes";
export { routes as mediaRoutes } from "./media.routes";
export { routes as chatRoutes } from "./chat.routes";
export { routes as settingsRoutes } from "./settings.routes";
export { routes as exploreRoutes } from "./explore.routes";
export { routes as staticRoutes } from "./static.routes";
export { routes as awardsRoutes } from "./awards.routes";
